# Generated by Django 3.0.5 on 2020-04-18 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realtor',
            old_name='hire_true',
            new_name='hire_date',
        ),
    ]
